version: "3.8"
services:
  bitcoin-core:
    build:
      dockerfile: ./bitcoind/Dockerfile
    image: bitcoind
    container_name: bitcoind
    command:
      - --testnet
      - -conf=/home/bitcoin/.bitcoin/bitcoin.conf
      - -pid=/home/bitcoin/.bitcoin/testnet3/bitcoind-testnet.pid
    volumes:
      - data:/home/bitcoin/.bitcoin
    expose:
      - 8332
      - 8333
      - 18332
      - 18333
      - 18444
    ports:
      - 18332:18332
      - 38332:38332
      - 38333:38333
    networks:
      - LN_testing

  core-lightning:
    build:
      dockerfile: ./Dockerfile
    image: lightningd
    container_name: lightningd
    command:
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcuser=rpcuser
      - --bitcoin-rpcpassword=VLSsigner1
      - --bitcoin-rpcport=18332
      - --network=testnet
      - --plugin-dir=/usr/libexec/c-lightning/plugins
      - --log-level=info
      - --max-locktime-blocks=288
      - --bind-addr=core-lightning:19735
      - --announce-addr=core-lightning:19735
    volumes:
      - clightning:/home/lightning/.lightning
      - data:/root/.bitcoin
    expose:
      - 9735
      - 9835
    ports:
      - 9735:9735
      - 9835:9835
      - 19735:19735
    networks:
      - LN_testing
    links:
      - bitcoin-core:bitcoind
    depends_on:
      bitcoin-core:
        condition: service_healthy
        restart: true
    environment:
      EXPOSE_TCP: "true"
      env_file: ./assets/testnet-env

volumes:
  data:
    name: bitcoin_data
    external: true
  clightning:

networks:
  LN_testing: