version: "3.8"
services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:23.0-alpine
    command:
      -testnet=1
      -server=1
      -rpcuser=rpcuser
      -rpcpassword=VLSsigner1
      -zmqpubrawblock=tcp://127.0.0.1:38332
      -zmqpubrawtx=tcp://127.0.0.1:38333
      -rpcport=18111
      -txindex=1
      -blockfilterindex=1
    volumes:
      # - host:container
      - data:/home/bitcoin/.bitcoin
    ports:
      # - host:container
      - 18332:18332
      - 18444:18444
      - 18443:18443

  core-lightning:
    build:
      dockerfile: ./Dockerfile
    command:
      -conf=/home/cln/.lightning/testnet-config
      -network=testnet
      -log-file=/home/cln/.lightning/testnet/lightning.log
    volumes:
      - data:/home/cln/.lightning
    depends_on:
      - bitcoin-core

volumes:
  data:
