version: "3.8"
services:
  bitcoin-core:
    build:
      dockerfile: ./bitcoind/Dockerfile
    image: bitcoind
    container_name: bitcoind
    command:
      - --testnet
      - -pid=/home/bitcoin/.bitcoin/testnet3/bitcoind-testnet.pid
    volumes:
      - data:/home/bitcoin/.bitcoin
    expose:
      - 8332
      - 8333
      - 18332
      - 18333
      - 18444
    ports:
      - 8333:8333
      - 18333:18333
      - 38333:38333
    networks:
      LN_testing:
        aliases:
          - bitcoind
    environment:
      - BITCOIN_CHAIN=test

  core-lightning:
    build:
      dockerfile: ./lightningd/Dockerfile
    image: lightningd
    container_name: lightningd
    command:
      - --conf=/home/lightning/.lightning/testnet-config
      - --bitcoin-rpcconnect=bitcoind
      - --bind-addr=core-lightning:19735
      - --announce-addr=core-lightning:19735
    volumes:
      - clightning:/home/lightning/.lightning
    expose:
      - 9735
      - 9835
    ports:
      - 9735:9735
      - 19735:19735
    networks:
      - LN_testing
    links:
      - bitcoin-core:bitcoind
    depends_on:
      bitcoin-core:
        condition: service_healthy
        restart: true
    env_file:
      - ./assets/testnet-env


volumes:
  data:
    name: bitcoin_data
    external: true
  clightning:
    name: lightning_data
    external: true

networks:
  LN_testing: